language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops-daniel
  api_key:
    secure: PNJ18Q+ZzGsSoUNMi9Rgj+An8mSSVvou1XqiX8O+h2p9adqFqUQEgHBV1fTnbAwsJncKvYPl0tCdxzC6whMcuAGbu0Y0IOqnsQTaNpyjYKMh/KH3koQf/14RCsd3V4uIOOWcmee1ZArzcjgDPRS4jI3Z1VBtiyYFpyaaxsav+hI0K60vy2JL5Vu+LSUFSu73xCE0ghrPs8c5j1RCJ6j7XqqYwxmra4NtCIDIPn1XGFfGGz28nQ9DSpWwAzmC8ir411BwDW7cKwRwiqRmqs/WLf9BMAjbkzYDFvPYjfDmiaWryM+gDgmkl2lVcgF6mD1HXn6EPM2X/z94P0I1e2uHBQvYvAa+iNj5HeAiBm/7xKsvaylStd8qBTw9EKUQPl3LdTTGkhgRKIs+s179eJMEOvtBKARiXhFQNIWzXReSa3eHHwct18ilMtUzmdgcM3xPxKDR7/RGOOtPl8P5P3ikzOtgsDB0OOZCWThNiMSwD+EJB3CX7IlZK+iK3453gadl6azrv2icHSdrBKxXCsi3BML+beFTiGp3ryNNPJ/w3a7l8SbtSZIzUEcU6J6QbfraX7yb3uK5QsAq/XXM2XQTMAPdvCOpx/Qm8Z4B3MG166w+BMQ/ja3W2pR0AJQyWEee5/0ortjO4RDUUKBrMzQxCcD/m1AgKdBPm7a4mthZZAg=
